### ISSUE TITLE
【May 9】淺入淺出 Deep generative model

### ISSUE THREAD

**Issue by sufuf3** [TGmeetup/TGmeetup.github.io#1]
# 淺入淺出 Deep generative model

https://www.meetup.com/pythonhug/events/250273230/

### 地點 / Location
Micro Beer 麥烤杯 @ 新竹
Micro Beer 麥烤杯 @ Hsinchu

### 日期 時間 / Date Time
星期三 5月 9日 2018年, 19 : 00 :clock7:
Wed May 9 2018, 19 : 00 :clock7:

### PyHUG
https://raw.githubusercontent.com/TGmeetup/TGmeetup/master/community/tw/PyHUG/package.json

---

> Pure data is right below
> Leave it!
<details>
{
  "name": "淺入淺出 Deep generative model",
  "datetime": "2018-05-09T11:00:00.000Z",
  "local_city": "Hsinchu County",
  "location": "Micro Beer 麥烤杯",
  "geocode": {
    "lat": 24.819185256958008,
    "lng": 121.02629852294922
  },
  "geocodeFromGroup": false,
  "link": "https://www.meetup.com/pythonhug/events/250273230/",
  "groupRef" : "community/tw/PyHUG"
}
</detail>

**Comment by qas612820704** [comment]
@sufuf3 , I updated date time format of event,

keep `datetime` or use `local_datetime` ?

```diff
- "local_date": "2018-05-09",
- "local_time": "19:00",
+ "datetime": "2018-05-09T11:00:00.000Z",
```

**Comment by sufuf3** [comment]
Let's use `datetime` Many thanks.

**Comment by qas612820704** [comment]
@sufuf3, 
Can Group Information part link to markdown, not json?

**Comment by sufuf3** [comment]
Is it fine that I create `https://github.com/TGmeetup/TGmeetup/blob/master/community/tw/DigitalOceanHsinchu/README.md`?
What do you think?

**Comment by qas612820704** [comment]
Yes! That's what I mean. Thanks

**Comment by qas612820704** [comment]
Because I want to implement RSS.

I think it is better move events(issues) to an independent  repo.

So i close it and move this to TGmeetup/TGevents#1.
